#### Importing Libraries

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision

In [37]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot
np.random.seed(42)
from IPython.core.debugger import set_trace
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
def func(x):
    result = x * x
    #Allows debugging
    #set_trace()
    return result

In [15]:
x = torch.rand(1, requires_grad=True)
y = func(x)
print(x)
print(y)

tensor([0.4159], requires_grad=True)
tensor([0.1730], grad_fn=<ThMulBackward>)


### Tensors

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
X = np.random.random((5,3))
X

array([[0.38867729, 0.27134903, 0.82873751],
       [0.35675333, 0.28093451, 0.54269608],
       [0.14092422, 0.80219698, 0.07455064],
       [0.98688694, 0.77224477, 0.19871568],
       [0.00552212, 0.81546143, 0.70685734]])

In [27]:
Y = torch.rand((5,3))
Y

tensor([[0.6878, 0.2766, 0.8725],
        [0.8971, 0.2722, 0.5063],
        [0.0321, 0.5461, 0.0502],
        [0.6107, 0.6629, 0.1971],
        [0.6099, 0.7107, 0.0800]])

In [28]:
X.shape

(5, 3)

In [29]:
Y.shape

torch.Size([5, 3])

In [30]:
X.T @ X

array([[1.27217893, 1.08536186, 0.72623933],
       [1.08536186, 2.05741382, 1.16701552],
       [0.72623933, 1.16701552, 1.52601792]])

In [32]:
Y.t() @ Y

tensor([[2.0238, 1.2903, 1.2250],
        [1.2903, 1.3934, 0.5940],
        [1.2250, 0.5940, 1.0654]])

In [38]:
inv(X. T @ X)

array([[ 1.45888562, -0.66369788, -0.18673069],
       [-0.66369788,  1.16034979, -0.57151538],
       [-0.18673069, -0.57151538,  1.18123023]])

In [42]:
torch.inverse(Y.t() @ Y)

tensor([[ 3.7306, -2.1326, -3.1006],
        [-2.1326,  2.1606,  1.2476],
        [-3.1006,  1.2476,  3.8083]])

In [45]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [46]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [47]:
A.add_(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [48]:
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

### Broadcasting

In [49]:
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [50]:
A[0,0]

tensor(2.)

In [51]:
A[0]

tensor([2., 1., 1.])

In [52]:
A[0:2]

tensor([[2., 1., 1.],
        [1., 2., 1.]])

### Converting

In [53]:
print(type(A))

<class 'torch.Tensor'>


In [59]:
#print(type(A.numpy())
a_numpy = A.numpy()
print(a_numpy)
print(type(a_numpy))

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
<class 'numpy.ndarray'>


In [60]:
t_tensor = torch.from_numpy(np.eye(3))
print(t_tensor)
print(type(t_tensor))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


## Autograd

In [61]:
from torch import autograd

In [63]:
w = torch.ones(3)
print(w)
w.requires_grad

tensor([1., 1., 1.])


False

In [ ]:
z = 